# Describes the format for available services for subaru
lights_jd:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

lights_stop_jd:
  description: >
    Stop flashing the lights of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn_jd:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

horn_stop_jd:
  description: >
    Stop sounding the horn of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

remote_start_jd:
  description: >
    Start the engine and climate control of the vehicle.  Uses the climate control settings saved. The vehicle is identified via
    the vin (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

remote_stop_jd:
  description: >
    Stop the engine and climate control of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

charge_start_jd:
  description: >
    Starts EV charging. This cannot be stopped remotely. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

update_jd:
  description: >
    Sends request to vehicle to update data. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001

fetch_jd:
  description: >
    Refreshes data (does not request update from vehicle). The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: JF2ABCDE6L0000001
